name: Cloud PC Bez PINu i CSRF
on: workflow_dispatch

jobs:
  run-pc:
    runs-on: windows-latest
    steps:
      - name: 1. Polaczenie Tailscale
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "ts.exe"
          Start-Process -FilePath ".\ts.exe" -ArgumentList "/quiet" -Wait
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --unattended

      - name: 2. Instalacja Sunshine Autokonfiguracja
        shell: powershell
        run: |
          winget install LizardByte.Sunshine --accept-source-agreements --accept-package-agreements
          $conf = "C:\Program Files\Sunshine\config"
          New-Item -ItemType Directory -Force -Path $conf
          
          # Wylaczamy PIN, logowanie oraz zabezpieczenie CSRF dla IP Tailscale
          Set-Content -Path "$conf\sunshine.conf" -Value "origin_pin_allowed = false`nrequire_pin = false`nauthentication = disabled"
          
          Start-Process -FilePath "C:\Program Files\Sunshine\sunshine.exe"

      - name: 3. Trzymanie sesji
        shell: powershell
        run: Start-Sleep -Seconds 20000
        
