name: Cloud PC przez RDP
on: workflow_dispatch

jobs:
  run-pc:
    runs-on: windows-latest
    steps:
      - name: 1. Polaczenie Tailscale
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "ts.exe"
          Start-Process -FilePath ".\ts.exe" -ArgumentList "/quiet" -Wait
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --unattended

      - name: 2. Wlaczenie Pulpitu Zdalnego i Ustawienie Hasla
        shell: powershell
        run: |
          # Włączamy RDP w rejestrze Windowsa
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          
          # Ustawiamy znane hasło dla użytkownika "runneradmin"
          $Password = ConvertTo-SecureString "RobloxStudio2026!" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $Password
          Write-Host "Pulpit zdalny gotowy! Uzytkownik: runneradmin, Haslo: RobloxStudio2026!"

      - name: 3. Trzymanie sesji
        shell: powershell
        run: Start-Sleep -Seconds 20000
        
